CREATE VIEW STUDENT_NUM AS
SELECT COUNT (*) 
FROM STUDENT S, ENROLLED E, COURSE C
WHERE S.sid = E.sid AND E.cid = C.cid AND S.major <> 'CS';
-- students without any major ?

CREATE VIEW NON_HEAVILY_CS_COURSE AS
SELECT *
FROM COURSE C
WHERE STUDENT_NUM < 100;



SELECT DISTINCT S.sid, S.name
FROM STUDENT S, NON_HEAVILY_CS_COURSE N, ENROLLED E
WHERE S.sid = E.sid AND E.cid = N.cid AND S.major = 'CS'
ORDER BY S.name DESC;