CREATE VIEW StudentPairs AS
SELECT DISTINCT S1.sid, S2.sid
FROM STUDENT S1, STUDENT S2, ENROLLED E1, ENROLLED E2
WHERE S1.sid = E1.sid AND S2.sid = E2.sid AND E1.cid = E2.cid AND S1.sid <> S2.sid
AND NOT IN (SELECT * FROM MEMBER M1, MEMBER M2
  			WHERE S1.sid = M1.sid AND S2.sid = M2.sid 
  			AND M1.pid = M2.pid);